name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: "Install dependencies"
      run: |
        sudo apt -y update
        sudo apt -y install meson libgtk-3-dev libalpm-dev libarchive-dev libcurl4-openssl-dev libgpgme-dev

    - name: Configure
      run: meson setup build -Dtracy_enable=false -Dbuildtype=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: meson compile -C build

    - name: Set Build number
      shell: bash
      run: echo "build_number=$(git rev-list HEAD --count)" >> $GITHUB_ENV

    - name: Compute git short sha
      shell: bash
      run: echo "git_short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create artifacts
      shell: bash
      run: |
        mkdir artifacts
        cp build/pepv artifacts/
        cp data/pepv.ui artifacts/
        cp data/pepv.desktop artifacts/
        cp data/icons/pepv.png artifacts/
        cp data/icons/sizes/* artifacts/
        

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pepv-${{ env.build_number }}-${{ env.git_short_sha }}
        path: artifacts/
